version: '3'

services:
  app:
    image: ferprojekt/php:8.1
    restart: unless-stopped
    volumes:
      - ./src:/var/www/

  nginx:
    image: ferprojekt/nginx
    restart: unless-stopped
    volumes_from:
      - app
    ports:
      - 8080:80

  mysql:
    # https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment: 
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
        MYSQL_USER: user
    volumes: 
        - ./.db_data:/var/lib/mysql
    ports: 
        - "3306:3306"